# 1) Tell Travis we need a copy of docker running
# 2) Build out image using "Dockerfile.dev"
# 3) Tell Travis how to run our test suite
# 4) Tell Travis how to deploy our code to AWS

# executing each command I need a root permissions
sudo: required
# travis-ci is gonna install a copy of docker into our running container
services:
  - docker

before_install:
  - docker build -t jurik99/docker-react -f Dockerfile.dev .

# tell Travis how to run our test suite
script:
  - docker run jurik99/docker-react npm run test -- --coverage # (-- --coverage) is used to print tests result and exit interactive mode.